### ISSUE TITLE
Consider renaming proxies

### ISSUE THREAD

**Issue by TrySound** [ds300/derivablejs#112]
Proxy name is really confusing for derivable users since javascript has a feature called Proxy. Can we rename proxies to lens back? Or maybe something else?
/cc @ds300

**Comment by ds300** [comment]
how about `DerivedAtom`?

**Comment by TrySound** [comment]
Or CompositeAtom?

**Comment by ds300** [comment]
`Composite` implies that it's made up of more than one atom, which is probably not true most of the time.

**Comment by TrySound** [comment]
Mediator, MidAtom, SubAtom?

**Comment by TrySound** [comment]
CompoundAtom similar to composite?

**Comment by TrySound** [comment]
Or even molecule ?

**Comment by TrySound** [comment]
Ah, DuplexDerive?@-^-@

**Comment by andreypopp** [comment]
Lens

**Comment by ds300** [comment]
Lens is ok with me.
