### ISSUE TITLE
Example code not work

### ISSUE THREAD

**Issue by sphynx79** [ds300/derivablejs#118]
Hi,

i try to use this simple code in derivable 2.0.0-beta.3, i take this code from documentation

``` javascript
import { derive, atom, setDebugMode } from "derivable"
setDebugMode(true)

const x = atom(4)
const times = (a, b) => a * b
const xTimesTwo = x.derive(times, 2)

console.log(xTimesTwo.get())

```
but result is NaN

until version 2.0.0-beta.1 this code work fine

**Comment by TrySound** [comment]
Additional arguments support was removed. Use function scope instead.
https://github.com/ds300/derivablejs/commit/371012e9e12358fb6ee936a0b287b6ff8689868f

**Comment by sphynx79** [comment]
``` javascript
const x = atom(4);
const times = (a, b) => a * b;
const xTimesTwo = x.derive((x)=> times(x,2));
```
in this way

**Comment by TrySound** [comment]
Yep, this way.

**Comment by sphynx79** [comment]
also if i preferer old way!!

Thanks.

**Comment by TrySound** [comment]
Docs is a bad side of this project. If you would like to help with it I'm open for questions.
