### ISSUE TITLE
Composite Lenses

### ISSUE THREAD

**Issue by ds300** [ds300/derivablejs#25]
At the moment 'lensed atoms' may only have one underlying atom. AFAICT there is no conceptual barrier to allowing more than one underlying atom, and only a minor implementation barrier. I propose adding an alternative to the [Lens](http://ds300.github.io/derivablejs/#derivable-Lens) interface:

```typescript
type CompositeLens<T> = {
  // no-arg getter uses lexical closure to deref and combine atoms
  get: () => T,

  // one-arg setter to tease apart the value being set and push it
  // up to the atoms manually
  // runs in an implicit transaction.
  set: (value: T) => void
}
```

Instances of which would be passed to a new top-level function `compositeLens` to create lensed atoms:

```typescript
const $FirstName = atom('John');
const $LastName = atom('Steinbeck');

const $Name = compositeLens({
  get: () => $FirstName.get() + ' ' + $LastName.get(),
  set: (val) => {
    const [first, last] = val.split(' ');
    $FirstName.set(first);
    $LastName.set(last);
  }
});

$Name.get(); // => 'John Steinbeck'

$Name.set('James Joyce').

$LastName.get(); // => 'Joyce'
```

**Comment by liron00** [comment]
So Atom::derive is to Derivation as Lens is to CompositeLens.

Yep I've had this idea too for a while too. I think of it as the converse of a derivation / a way to call .set on a derivation.

I think your approach here is good.

**Comment by ds300** [comment]
> So Atom::derive is to Derivation as Lens is to CompositeLens.

Exactly, yes.

> I think your approach here is good.

Thanks :) I'm now mulling over whether to make a new 1-arity version of the top-level `lens` function for this rather than adding `compositeLens`.
