### ISSUE TITLE
Declarative control of Reactor lifecycles

### ISSUE THREAD

**Issue by ds300** [ds300/derivablejs#29]
Imperatively controlling the lifecycles of Reactors (using the`Reactor#start` and `Reactor#stop` methods) feels wrong to me lately. It is somewhat verbose and, more importantly, it goes against the grain of this whole declarative/reactive thing we have going with Observables and Derivables.

My positive experiences with `Derivable#reactWhen` imply a better way: providing a lifetime configuration object as a second argument to the `.react` method (and also making the method void). Here is the proposed api:

```javascript
interface ReactorConfig {
  when?: Derivable<any>,
  until?: Derivable<any>,
  force?: boolean | Derivable<any>,
  once?: boolean,
  onStart?: () => void,
  onStop?: () => void
}

interface Derivable<T> {
  react(cb: (v: T) => void, config?: ReactorConfig): void;
}
```

`when` would cause `.start` and `.stop` to be called when the derivable becomes truthy and falsey respectively.

`until` would cause the reactor to be stopped (such that it may never be started again) when the derivable becomes truthy.

`force`, if truthy, would cause the reactor to be `.force()`ed whenever being `.start()`ed. It would be `true` by default.

`once` would cause the reactor to be stopped (such that it may never be started again) immediately following its first reaction.

`onStart` and `onStop` would be used as before.

Example usage:

```typescript
const $Num = atom(4);

$Num.react(n => console.log(n), {
  when: $Num.derive(n => n < 10),
  until: $Num.is(null),
});
// $> 4

$Num.set(9);
// $> 9

$Num.set(10);
// ... no output

$Num.set(0);
// $> 0

$Num.set(null);
// ... no output

$Num.set(5);
// ... no output
```

This has two major benefits as far as I can tell:

- It is both declarative and concise. This makes it easy to read and reason about.
- It eliminates the opportunity for inadvertently creating memory leaks.

I'm not totally sure whether all bases are covered here, so it seems prudent to leave the `.reactor` method alone for now. My hope is that I can get rid of it one day and have exclusively declarative control over Reactors.

**Comment by liron00** [comment]
Looks good. Perhaps for the derivable-type arguments, accept a function as
an "anonymous derivation" to make the code more compact.


On Saturday, December 12, 2015, David Sheldrick <notifications@github.com>
wrote:

> Imperatively controlling the lifecycles of Reactors (using the
> Reactor#start and Reactor#stop methods) feels wrong to me lately. It is
> somewhat verbose and, more importantly, it goes against the grain of this
> whole declarative/reactive thing we have going with Observables and
> Derivables.
>
> My positive experiences with Derivable#reactWhen imply a better way:
> providing a lifetime configuration object as a second argument to the
> .react method (and also making the method void). Here is the proposed api:
>
> interface ReactorConfig {
>   when?: Derivable<any>,
>   until?: Derivable<any>,
>   force?: boolean | Derivable<any>,
>   once?: boolean,
>   onStart?: () => void,
>   onStop?: () => void
> }
>
> when would cause .start and .stop to be called when the derivable becomes
> truthy and falsey respectively.
>
> until would cause the reactor to be stopped (such that it may never be
> started again) when the derivable becomes truthy.
>
> force, if truthy, would cause the reactor to be .force()ed whenever being
> .start()ed. It would be true by default.
>
> once would cause the reactor to be stopped (such that it may never be
> started again) immediately following its first reaction.
>
> onStart and onStop would be used as before.
>
> Example usage:
>
> const $Num = atom(4);
>
> $Num.react(n => console.log(n), {
>   when: $Num.derive(n => n < 10),
>   until: $Num.is(null),
> });// $> 4
>
> $Num.set(9);// $> 9
>
> $Num.set(10);// ... no output
>
> $Num.set(0);// $> 0
>
> $Num.set(null);// ... no output
>
> $Num.set(5);// ... no output
>
> This has two major benefits as far as I can tell:
>
>    - It is both declarative and concise. This makes it easy to read and
>    reason about.
>    - It eliminates the opportunity for inadvertently creating memory
>    leaks.
>
> I'm not totally sure whether all bases are covered here, so it seems
> prudent to leave the .reactor method alone for now. My hope is that I can
> get rid of it one day and have exclusively declarative control over
> Reactors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ds300/derivablejs/issues/29>.
>


-- 
--
*Liron Shapira*, Chief Science Officer
US: +1 408.621.6667 | 303 Bryant St, Mountain View, CA 94041
Israel: +972 54.457.5776 | Azrieli Round Tower Fl 29, 132 Menachem Begin
Rd, Tel Aviv, Israel 67021
<http://i.imgur.com/dpMvVRI.png>

**Comment by ds300** [comment]
@liron00 good idea :+1:

**Comment by ds300** [comment]
I've been thinking hard about this, and have an implementation. The ReactorConfig interface now looks like this:

```typescript
interface ReactorConfig {
  from?: Derivable<any>,
  when?: Derivable<any>,
  until?: Derivable<any>,
  force?: boolean | Derivable<any>,
  once?: boolean,
  skipFirst?: boolean,
  onStart?: () => void,
  onStop?: () => void
}
```

The additions are:

- `from`, lets one specify a 'starting' condition which is used exactly once to determine the start of the reactor's lifecycle. i.e. when `from` becomes truthy, the reactor is initialized and `from` is no longer listened to. This decouples initialization time from declaration time, which I think could turn out to be very useful.
- `skipFirst`, like `force: false` allows one to initialize a reactor without incurring the initial reaction, but also allows the semantics of `force: true` to take hold after initialization.

This now feels like I've now got the vast majority of use cases covered, if not all of them.

**Comment by liron00** [comment]
Hm I don't understand what happens with the combination `{skipFirst: false, force: true}`.

**Comment by ds300** [comment]
`skipFirst` literally just ignores the first (and only the first) invocation of your reactor function. You could implement it as a wrapper function, i.e:

```javascript
function skipFirst (f) {
  let skipped = false;
  return v => {
    if (skipped) f(v);
    else skipped = true;
  }
}

d.react(skipFirst(f));

// is equivalent to
d.react(f, {skipFirst: true});
```

While `force` applies to every time the reactor is `.start`ed (as a result of changes in the `when` option)

Your query gives me pause, however. There *is* something icky about the crossover in concerns here.   

I think, crucially, that having a `skipFirst` option means that the `force: false` option will be used vanishingly rarely, so it might be cleanest to not include it. After all, it's functionality can also be replicated in 'userland':

```javascript
function forceFalse (f) {
  let skip = false;
  const onStart = () => { skip = true; };
  return [onStart, v => {
    if (skip) skip = false;
    else f(v);
  }];
}

const [onStart, f] = forceFalse(v => {...side effects...});

d.react(f, {onStart});
```

This will require some thought. Thank you.
