### ISSUE TITLE
Pass current value into when/until/etc

### ISSUE THREAD

**Issue by ncammarata** [ds300/derivablejs#33]
Posting this for discussion.

I end up writing a lot of code like this

``` js
activeError.react(show, { when: (() => activeError.get() !== null) })
```

it would be nice to write

``` js
activeError.react(show, { when: notEq(null) })
```

**Comment by ds300** [comment]
Of course any reduction in line noise is very desirable, but this change would conversely make it more verbose to define anonymous from/when/until conditions which do not depend directly on the derivable being reacted to. It is not obvious whether this tradeoff would be worth it, so I'm inclined to keep thinking about this one for a while.

**Comment by liron00** [comment]
Maybe the common pattern we can abbreviate is specifically
`derivable.reactNonNull()`.

--
*Liron Shapira*, Chief Science Officer
US: +1 408.621.6667 | 303 Bryant St, Mountain View, CA 94041
Israel: +972 54.457.5776 | Azrieli Round Tower Fl 29, 132 Menachem Begin
Rd, Tel Aviv, Israel 67021
<http://i.imgur.com/dpMvVRI.png>

**Comment by ds300** [comment]
I'd go with `mReact` for the sake of consistency (with `mDerive` et al; the `m` stands for Maybe), but yeah I'd be much more open to doing that.

in the meantime, of course, you can implement your own version:

```javascript
function coerce(x) {
  if (isDerivable(x)) {
    return x;
  } else if (typeof x === 'function') {
    return derivation(x);
  }
}
function mReact(derivable, effectFn, lifecycle={}) {
  const when = derivable.mAnd(coerce(lifecycle.when) || true);
  return derivable.react(effectFn, Object.assign({}, lifecycle, {when}));
}

mReact(activeError, show);

// or combining with some other condition

mReact(activeError, show, {when: $someOtherCondition});
```

**Comment by ncammarata** [comment]
it's currently passing no arguments to when/until/etc right? Why would passing an argument make it harder to not use the argument. You could still write

```activeError.react(show, { when: () => Math.random() >  .5 })```

**Comment by ds300** [comment]
That would be equivalent to:

```typescript
activeError.react(show, {
 when () {
  activeError.get();
  return Math.random() > 0.5;
});
```

That unused dereference of `activeError` has two important consequences:

- the `when` condition gets re-evaluated every time activeError changes, which might not be desirable
- If `activeError` is a derivation it might be evaluated at an inappropriate time (i.e. a time which is appropriate for the `when` condition but not for `activeError`), which could throw errors.

**Comment by ncammarata** [comment]
Ah, completely forgot it's doing dependency tracking. Makes sense.

**Comment by liron00** [comment]
Incidentally, `derivable.mReact` is exactly the shortcut I would be using in every implementation of my controlled component pattern.
