### ISSUE TITLE
API for tracking reads

### ISSUE THREAD

**Issue by andreypopp** [ds300/derivablejs#39]
I'm thinking of integration with React in which some decorator wraps component's render method to collect all atoms/derivables which were derefernced in the method body (during execution) and then sets up a corresponding one-shot reactions so that component re-renders once any of the values change.

What do you think of this approach? Is there any API available to do that?

**Comment by ds300** [comment]
Sounds very similar to [jevakallio/react-derivable](https://github.com/jevakallio/react-derivable) :)

**Comment by andreypopp** [comment]
That's awesome!

Am I right that `.get()` calls are tracked when called from within `.derive(cb)` callbacks?

**Comment by ds300** [comment]
> Am I right that .get() calls are tracked when called from within .derive(cb) callbacks?

Yes. The `.derive` method is sugar for the fundamental `derivation` function, which is where all the tracking happens. 

So here is actually how to solve your original problem in a similar way to react-derivable, using `derivation` (I haven't tested this, but 99.999% sure it'd work barring syntax errors):

```js
function WrapDerivable (component) {
  // we need to wrap willMount, render, and didUnmount
  const _willMount = component.componentWillMount;
  const _render = component.render;
  const _didUnmount = component.componentDidUnmount;

  component.componentWillMount = function () {
    _willMount && _willMount.apply(this);
    this.$mounted = atom(true);

    derivation(() => _render.apply(this)).react(
      vdom => this.setState({__vdom: vdom}),
      {when: this.$mounted}
    );
  };

  component.render = function () {
    return this.state.__vdom;
  };

  component.componentDidUnmount = function () {
    _didUnmount && _didUnmount.apply(this);
    this.$mounted.set(false);
  };

  return component;
}
```

You'd have to modify this to wrap prototype functions if you want to use it with class syntax.

**Comment by andreypopp** [comment]
To be honest I'm a little bit worried with the approach of memozing of the render result. That probably could lead to some inconsistencies between derivable managed atoms and React props. I'm not sure yet as it is difficult to reason about two concurrent scheduling systems. That's why I'd rather to see a reaction which just does `forceUpdate`.

**Comment by ds300** [comment]
You are right on the money. It wouldn't work if you wanted to use react's own state or props to also trigger renders.

Your suggestion is much better:

```js
function WrapDerivable (component) {
  const _willMount = component.componentWillMount;
  const _didUnmount = component.componentDidUnmount;

  component.componentWillMount = function () {
    _willMount && _willMount.apply(this);
    this.$mounted = atom(true);

    derivation(() => _render.apply(this)).react(
      this.forceUpdate()
      {when: this.$mounted}
    );
  };

  component.componentDidUnmount = function () {
    _didUnmount && _didUnmount.apply(this);
    this.$mounted.set(false);
  };

  return component;
}
```

**Comment by andreypopp** [comment]
@ds300 awesome, thank you

**Comment by andreypopp** [comment]
This is what I'm ended up with https://github.com/prometheusresearch/react-forms/blob/subscription/src/reactive/reactive.js

Note the line https://github.com/prometheusresearch/react-forms/blob/subscription/src/reactive/reactive.js#L22

This is required so render doesn't run multiple times but instead only values are probed for equality. This is to satisfy this invariant: https://github.com/prometheusresearch/react-forms/blob/subscription/src/reactive/__tests__/reactive-test.js#L167

**Comment by andreypopp** [comment]
@ds300 any suggestions to get rid of accessing to `_parents` directly? I guess this is exactly what I meant by API for tracking reads. I need to get list of derivables which are parents for a given derivable (render) and when react when any of the values is such list has changed (race).

**Comment by ds300** [comment]
I can't think of a legit way of tracking parents directly. 

I can think of one way to solve the duplicate renders problem, by kinda combining my previous two examples. I've actually tested it this time :D

```js
import React, { Component } from 'react';
import {derivation, atom} from 'derivable';

const NO_VDOM = Symbol('no vdom here buddy');

function wrapComponentDefinition (component) {
  const _willMount = component.componentWillMount;
  const _didUnmount = component.componentDidUnmount;
  const _render = component.render;

  component.componentWillMount = function () {
    _willMount && _willMount.apply(this);
    this.$mounted = atom(true);
    this.__vdom = NO_VDOM;

    derivation(() => _render.call(this)).react(
      vdom => {
        this.__vdom = vdom;
        this.forceUpdate();
        this._vdom = NO_VDOM;
      },
      {when: this.$mounted}
    );
  };

  component.render = function () {
    return this.__vdom === NO_VDOM ? _render.call(this) : this.__vdom;
  };

  component.componentWillUnmount = function () {
    _didUnmount && _didUnmount.apply(this);
    this.$mounted.set(false);
  };

  return component;
}

function wrapClass (klass) {
  wrapComponentDefinition(klass.prototype);
  return klass;
}

function wrapFunction (_render) {
  return React.createClass(wrapComponentDefinition({render: function () {
    return _render(this.props);
  }}));
}

export default function wrap (thing) {
  if (typeof thing.prototype.render === 'function') {
    return wrapClass(thing);
  } else if (typeof thing === 'function') {
    return wrapFunction(thing);
  } else if (typeof thing.render === 'function') {
    return wrapComponentDefinition(thing);
  }
};
```

I should also probably let you know that the `.reactor` method is almost certainly disappearing soon, and there will be no sanctioned way to get a reference to reactors. The reason for this is that I'm now mostly convinced that reactors can be better managed with the declarative lifecycle controls for all use cases, at least after learning how to do it. I'll be writing some tutorials on that subject over the next month or so.

**Comment by andreypopp** [comment]
Hm... I'm still not sure this will work as:
* `this.forceUpdate()` could be possibly async (even if it's not it could if we do `batchedUpdates()`)
* In some cases when props are also updating it could be the case the `render()` reacts with the old props (again with batching). This is exactly why I've tried to make render be called by React and not by derivable, because React does it own scheduling.

**Comment by ds300** [comment]
Hm, OK. I don't see a neat solution with the existing API then.

I also just noticed that your approach will stop working in 1.0.0 because now parents are only tracked for derivations which are upstream of reactors.

I suppose it would be entirely feasible to offer a function called `track`, which takes a thunk, executes it, and returns an array of the derivables which were dereferenced. I'll seriously think about putting that in 1.0.0.

**Comment by ds300** [comment]
Well I've called it `captureDereferences` instead of `track`, but it will be in the 1.0.0 release 🎉

**Comment by andreypopp** [comment]
Thank you! Looking forward to the release!

**Comment by andreypopp** [comment]
I'm seeing it returns a list of derivations, but the use case for the API is probably just a way to setup some reaction when one of the values change. Do you think it would be better if it would return some kind of an object with just `.react()` method?

**Comment by ds300** [comment]
You can do that with `struct`.

```js
struct(captureDereferences(myFn)).react(meReactionFn);
```

And, if you only want it to run once *next* time they change: 

```js
struct(captureDereferences(myFn)).react(meReactionFn, {skipFirst: true, once: true);
```

**Comment by andreypopp** [comment]
Right, just thought that returning an opaque object could be better as it reduces API surface. Also it seems like `struct(captureDereferences(fn))` would be the only way one uses `captureDereferences` API. Maybe I'm missing something though...

**Comment by ds300** [comment]
You might be right. Or maybe one day someone will want to know exactly which derivables are dereferenced `¯\_(ツ)_/¯`

This is extremely niche API territory in the first place, so I'm not too concerned about reducing API surface. I can't even think of a name to give to the composition of `struct` and `captureDereferences` (any ideas?).

**Comment by andreypopp** [comment]
>  I can't even think of a name to give to the composition of struct and captureDereferences (any ideas?).

Maybe just `capture`?

**Comment by andreypopp** [comment]
I still feel that having `Reactor` class exposed is a good thing as it more aligns with the original use case of integrating with the external schedulers (like React).

Using 1.0.0 beta8 I ended up with this implementation of reactive components:
```
function reactive(Component) {
    return class extends Component {

      static displayName = Component.displayName || Component.name;

      constructor(props, context) {
        super(props, context);
        this.disactivate = null;
        this.reactor = null;
      }

      render() {
        this.disactivate = atom(false);
        let element;
        this.reactor = capture(() => {
          element = super.render()
        });
        this.reactor.react(() => {
          this.forceUpdate();
        }, {
          once: true,
          skipFirst: true,
          until: this.disactivate,
        });
        return element;
      }

      componentWillUpdate(...args) {
        this.disactivate.set(true);
        if (super.componentWillUpdate) {
          super.componentWillUpdate(...args);
        }
      }

      componentWillUnmount(...args) {
        this.disactivate.set(true);
        if (super.componentWillUnmount) {
          super.componentWillUnmount(...args);
        }
      }

    };
}
```
This works well, but notice how many things I should do to correctly setup reaction to update the component. Also each component update it would allocate a lot! Instead if I had access to Reactor class, I could just start/stop it and when needed — swap underlying derivable.

**Comment by andreypopp** [comment]
Ok, I experimented with a custom build of derivable which exposes `Reactor` and built two versions of `reactive` decorator for React components, one which re-creates reactor on each `render()` and another which re-uses the same reactor.

#### Benchmark results

```
Fast (use Reactor directly) x 88,599 ops/sec ±1.76% (77 runs sampled)
Naive (use public API and re-create reactors) x 48,234 ops/sec ±2.22% (79 runs sampled)
Fastest is Fast (use Reactor directly)
```

I get those numbers with Node 6 consistently on my macbook. Using Reactor directly is twice as fast!

#### Code

Naive implementation: https://github.com/andreypopp/react-reactive/blob/fast/src/index.js
Fast implementation: https://github.com/andreypopp/react-reactive/blob/fast/src/fast.js

#### How-to benchmark

```
% git clone git@github.com:andreypopp/react-reactive.git
% cd react-reactive
% npm install
% make benchmark
```

**Comment by ds300** [comment]
I hid the `Reactor` class because it is entirely useless for 99% of cases and merely *helpful* for the others. This is definitely one of the cases where it is helpful, but I've actually never encountered such situations when writing application code, only framework code. I think framework authors can be relied upon to use work arounds. Sure it's more awkward, but I think you can still make it fast. Here's my attempt at your thing:

```js
export function reactive(Component) {
  return class extends Component {

    static displayName = Component.displayName || Component.name;

    constructor(props, context) {
      super(props, context);

      this.dependencies = atom([]);
      this.alive = atom(false);
      this.skipNextUpdate = true;

      var epoch = 0;

      this.dependencies
        .derive(ds => {
          ds.forEach(d => d.get())
          return epoch++; // trigger change without allocating a new array
        })
        .react(() => {
          if (this.skipNextUpdate) {
            this.skipNextUpdate = false;
          } else {
            this.forceUpdate();
          }
        }, {
          from: this.alive,
          until: this.alive.not(),
        });
    }

    componentWillMount(...args) {
      this.skipNextUpdate = true;
      this.alive.set(true);

      if (super.componentWillMount) {
        super.componentWillMount(...args);
      }
    }

    render() {
      let element;
      this.skipNextUpdate = true;
      this.dependencies.set(captureDereferences(() => {
        element = super.render()
      }));
      return element;
    }

    componentWillUnmount(...args) {
      this.alive.set(false);
      if (super.componentWillUnmount) {
        super.componentWillUnmount(...args);
      }
    }
  };
}
```

I didn't benchmark it yet

**Comment by andreypopp** [comment]
Added your impl but tests do not pass (`Error: Synchronous cyclical reactions disallowed. Use setImmediate.`). Also added mobx (w/ mobx-react) to benchmark.

**Comment by ds300** [comment]
oh yeah. Interesting I don't get that error when using it in the browser, but it makes sense because if `.forceUpdate` calls `.render` synchronously then `.dependencies` gets `.set` which triggers a cyclical reaction. I guess adding a setTimeout somewhere in there would ruin the benchmarks?

**Comment by andreypopp** [comment]
Yeah, `setTimeout` introduces asynchrony and will make it all complicated: React batching won't work anymore, multiple components will update in different ticks probably and so on.

**Comment by ds300** [comment]
Well I disabled the cycle check and got these results:

```
Naive (use public API and re-create reactors) x 53,722 ops/sec ±2.37% (81 runs sampled)
Fast (use Reactor directly) x 86,745 ops/sec ±1.90% (84 runs sampled)
Smart x 84,088 ops/sec ±1.87% (84 runs sampled)
MobX x 90,147 ops/sec ±2.02% (82 runs sampled)
Fastest is MobX
```

**Comment by andreypopp** [comment]
I guess by disabling cycle check you mean you patched derivable's code?

Still I think using `Reactor` is much more straightforward and efficient at the same time. Any chance you could expose it? I understand that this is undesirable to use by end-user apps but it looks like a useful enough primitives for writing bindings and other low-level constructs.

**Comment by ds300** [comment]
> I guess by disabling cycle check you mean you patched derivable's code?

Yeah. But I won't incorporate that into derivable itself.

I guess you're right about Reactor. I just really don't want to have it in the documentation. Would you be interested in having it as an undocumented (but guaranteed to stick around) feature?

**Comment by andreypopp** [comment]
> Would you be interested in having it as an undocumented (but guaranteed to stick around) feature?
Yes, that would be fine.

**Comment by ds300** [comment]
ok. `derivable@beta9` now has the Reactor constructor exposed as `__Reactor` 👍

**Comment by andreypopp** [comment]
After all, I see the need in `captureDereferences` in the current form (returns a list of derivables), see https://github.com/andreypopp/react-reactive/blob/master/src/index.js#L155-L168 for a smart `shouldComponentUpdate` optimisation which uses that.
