### ISSUE TITLE
Flow typings

### ISSUE THREAD

**Issue by andreypopp** [ds300/derivablejs#40]
I notice that you provide [TypeScript typings](https://github.com/ds300/derivablejs/blob/master/dist/derivable.d.ts) in the distribution.

I'm the user of [Flow](https://flowtype.org) and I request also including Flow typings with the distribution. It should be as easy as adding `dist/derivable.js.flow` with needed declarations.

I'd like to make a pull request with this functionality.

But first a question: How do you see this should be implemented? I see TypeScript typings are automatically generated from edn API description, do you think Flow typings should be generated as well? I'm afraid there would be some difficulties with that. Not because of a different syntax (that's easy to tweak with the generator) but because of the Flow type system being more expressive and thus different signatures in the output.

**Comment by ds300** [comment]
> But first a question: How do you see this should be implemented?

Well a first step would just be to copy the code that generates the [typescript file](https://github.com/ds300/derivablejs/blob/master/docgen/src/docgen/typescript.cljs) and patch it until it produces valid flow typings. Then if you need to support more subtle features than are currently expressible with my .edn DSL, you'd need to modify the [`docgen/src/ast.cljs`](https://github.com/ds300/derivablejs/blob/master/docgen/src/docgen/ast.cljs) file and make sure the typescript and html generators also know how to ignore/render those features...

All in all, it will almost certainly end up being much much much less work to just write it manually and keep it up to date manually. I'd be thrilled to get a PR for either though :)
