### ISSUE TITLE
How to convert observable to derivable?

### ISSUE THREAD

**Issue by zerkalica** [ds300/derivablejs#44]
from #42 

I need subscribe atom to observable if something listens my atom and unsubscribe, if nobody listens.
Unsubscribe atom on observer complete call.

How to use reactor in this case?

```js
class AtomObserver<V> {
    _setValue: (val: V) => void;
    _stop: () => void;

    constructor(
        setValue: (val: V) => void,
        stop: () => void
    ) {
        this._setValue = setValue
        this._stop = stop
    }

    next(v: V): void {
        this._setValue(v)
    }

    complete(v?: ?V): void {
        if (v) {
            this._setValue(v)
        }
        this._stop()
    }

    error(err: Error): void {
        // @todo: handle errors in derivable
        throw err
    }
}

class ObservableReactor<V> extends Reactor<V> {
    _observable: Observable<V, Error>;
    _sub: ?Subscription;
    _setValue: (val: V) => void;

    constructor(
        setValue: (val: V) => void,
        observable: Observable<V, Error>
    ) {
        super()
        this._setValue = setValue
        this._observable = observable
    }

    _stop = () => this.stop();

    onStart(): void {
        this._sub = this._observable.subscribe(new AtomObserver(this._setValue, this._stop))
    }

    onStop(): void {
        if (this._sub) this._sub.unsubscribe()
    }
}

function atomExt<V>(
    v: V,
    observable: Observable<V, Error>
): Atom<V> {
    const va: Atom<V> = atom(v)
        const setValue = (val: V) => {
            va.set(val)
        }
        const or = new ObservableReactor(setValue, observable)

        // something wrong here
        const r = va.reactor(or)
        r.start()

    return va
}

const v = 'test1'
const o = new Observable((observer) => {
  observer.next('test2')
  observer.complete('test3')
})
const a = atomExt(v, o)

a.react((v) => {
  console.log(v)
})
// outputs only test1
```

**Comment by andreypopp** [comment]
Just curious what's the use case behind this? Specifically:
> I need subscribe atom to observable if something listens my atom and unsubscribe, if nobody listens.

**Comment by zerkalica** [comment]
1. begin render widget -> start listening websocket -> observable + default value -> atom + reactor -> atom for updating widget state, reactor controlled by widget lifecycle

2. close widget -> stop reactor -> unsubscribe observable -> stop stop listening websocket

3. websocket complete -> observable.complete -> stop reactor

**Comment by ds300** [comment]
Hey! :) It's cool to see you using Derivable. Jus a heads up to begin with: you should probably avoid using the `Reactor` class. It is a really clunky piece of API design on my part and is going away in version 1.0.0. Much better is to use declarative lifecycle controls instead. They totally simplify controlling reactors in 99.9% of cases, like this one.

For example, does this solve your problem?

```js
class Widget extends React.Component {
  componentDidMount() {
    fetchAtom = atom({name: test});
    this.mounted = atom(true);
    let sub;
    
    this.mounted.react(mounted => {
      if (mounted) {
        sub = this._fetch('/url');
      } else {
        sub.unsubscribe();
      }
    });

    struct({
      model: fetchAtom,
      data: this._atomState
    }).react(v => this.setState(v), {
      when: this.mounted
    });
  }
  componentWillUnmount() {
    this.mounted.set(false);
  }
  render() { return ...}
}
```

btw, if you're using DerivableJS with React, consider checking out [andreypopp/react-derivable](https://github.com/andreypopp/react-derivable). It's seriously good and means you don't need to worry about manually calling .setState in reactors.

**Comment by zerkalica** [comment]
What if componentDidMount called 1000 times ?
.react() doesn't produce memory leak?
_atomState - delegated from outside.

**Comment by ds300** [comment]
> What if componentDidMount called 1000 times ?

Then you should submit a bug report because the [docs claim that componentDidMount is invoked only once](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount).

> .react() doesn't produce memory leak?

Active reactors are tied to their atoms. So is there is no `when: this.mounted` lifecycle condition and `this._atomState` is global, then the reactor is tied to `this._atomState`.

But because there is a `when` condition which becomes false when the component is unmounted, the reactor becomes 'partially' inactive. This means it is tied only to the atoms mentioned in the lifecycle conditions, which are also component-local in this case.

To fully deactivate a reactor, use the `until` condition. When `until` becomes true, all ties are broken and the reactor is eligible for garbage collection.

```js
    struct({
      model: fetchAtom,
      data: this._atomState
    }).react(v => this.setState(v), {
      until: this.mounted.not()
    });
```

In this case `until` is not strictly necessary, but it is good practice to use it as often as possible.

**Comment by zerkalica** [comment]
Thanks, "until" works. I create another question: #45
