### ISSUE TITLE
How to get derivable of derivable

### ISSUE THREAD

**Issue by zerkalica** [ds300/derivablejs#45]
``` js
type Status = string
type Subj = {status: Derivable<Status>}

const arr: Derivable<Subj>[]  = [
  atom({status: atom('loaded')}),
  atom({status: atom('pending')}),
]

const statuses: Derivable<Status[]> = struct(arr).derive(obj => obj.status.get())
```

How to get `Derivable<Status[]>` from `Derivable<Subj>[]` without using obj.status.get() ?

**Comment by ds300** [comment]
should that be

```js
const statuses: Derivable<Status[]> = struct(arr)
  .derive(subjs => subjs.map(obj => obj.status.get()))
```

?

But anyway, that seems fine to me. Not sure why you'd want to avoid using `obj.status.get()`?

Another way to do this would presumably be:

```js
const statuses = derivation(() => arr.map(subj => subj.get().status.get()))
```

And if you want automatic recursive dereferencing, you can modify the source of `struct` by just one line:

```js
function deepUnpack (thing) {
  if (isDerivable(thing)) {
    // this is the line that changed. Now it does recursive
    return deepUnpack(thing.get());
  } else if (Array.isArray(thing)) {
    return thing.map(deepUnpack);
  } else if (thing.constructor === Object) {
    var result = {};
    var keys = Object.keys(thing);
    for (var i = keys.length; i--;) {
      var prop = keys[i];
      result[prop] = deepUnpack(thing[prop]);
    }
    return result;
  } else {
    return thing;
  }
}

export function deepStruct (arg) {
  if (arg.constructor === Object || arg instanceof Array) {
    return derivation(function () {
      return deepUnpack(arg);
    });
  } else {
    throw new Error("`deepStruct` expects plain Object or Array");
  }
};
```

and then you could do

```js
const statuses = deepStruct(arr).derive(xs => xs.map(x => x.status));
```

Thinking about it, I suppose it would be fine to add an optional `recursive` parameter to `struct`. Thanks for the idea.

**Comment by zerkalica** [comment]
If i return pure value obj.status.get() in derive(), how to handle changes in obj.status?
Or inside derive some black magic with globals, like in derivation?

**Comment by ds300** [comment]
I wouldn't call it black magic, but yes. `.derive` is implemented on top of `.derivation`. So all calls to `.get` in functions passed to `.derive` will be intercepted, and changes will be propagated in the expected way.

**Comment by zerkalica** [comment]
Ok, thanks.

Black magic - i mean, that this trick based on specific single-threading javascript model. Our context, where we store dependencies between atoms is global.

**Comment by zerkalica** [comment]
If it's interesting for you - i experimented on dependency injection pattern (like di in angular2) and create library on top of derivablejs for buiding complex applications. It's still experiment, but i start use it in production.

https://github.com/zerkalica/reactive-di
