### ISSUE TITLE
Errors with example code in README

### ISSUE THREAD

**Issue by mruzekw** [ds300/derivablejs#47]
Hi, I'm typing out and following the example code in the README to grok DerivableJS.

While doing so, I run into a couple of issues.

First, I'm getting `"Hello, [object Object]"` as the output.

Second, I'm getting an error when trying to set the `name`: `TypeError: name.set is not a function`

I must be missing something. Looking forward to your response.

**Comment by ds300** [comment]
Hi, apologies for the delayed reply.

Can I see your code? [Here is an example of the readme code working as expected](http://requirebin.com/?gist=991784e3485cf1d5618d0bd332b28017)

**Comment by mruzekw** [comment]
Here's my JSBin: http://jsbin.com/yiwewimeda/edit?js,console

Will Mruzek
willmruzek.com
linkedin.com/in/willmruzek

**Comment by ds300** [comment]
This is a JSBin bug. It's overwriting the `name` variable with a `String` object somehow. Change the variable name to something else and it works.

**Comment by ds300** [comment]
Turns out this is a browser thing, not a JSBin thing!

**Comment by mruzekw** [comment]
Wow interesting. Thanks for investigating.
