### ISSUE TITLE
Question about recapturing parents implementation

### ISSUE THREAD

**Issue by mhsekhavat** [ds300/derivablejs#50]
Hi. With a derivation like this:

``` es6
const x = atom(1),
      y = atom(2),
      z = atom(true);

const d = derivation(() => {
    if (z.get())
        return x.get();
    else
        return y.get();
});
```

It seems that `parents_capturingParents` can not capture parent `y`, because `z.get()` returns `true` and `y.get` is not invoked at all. Are parents of `d` recaptured after atom `z` changes?

**Comment by andreypopp** [comment]
Right, but the result of `d` won't change if `y` changes without changing `z` to being `false`.

**Comment by andreypopp** [comment]
> Are parents of d recaptured after atom z changes?

Yes.

**Comment by mhsekhavat** [comment]
Aha. I have not profiled, but maybe it can improve performance to explicitly define parents for some of frequently changing derivatives and do not recapture their parents on every change. Example:
```es6
const x = atom(1),
      y = atom(2),
      z = atom(true);

const d = derivation([x, y, z], (xValue, yValue, zValue) => {
    if (zValue)
        return xValue;
    else
        return yValue;
});
```

**Comment by mhsekhavat** [comment]
Also an implicit method for being able to capture dependencies only once is something like:
```

**Comment by andreypopp** [comment]
Note that with the API you proposed derivation `d` will re-execute when `y` changes even if it doesn't influence `d`'s result.

Still knowing statically the dependencies of derivation can lead to useful optimisations, just not in that case, probably.

**Comment by mhsekhavat** [comment]
Yeah you're right. Actually I think it is a trade-off between overhead of recomputing dependencies dynamically and redundantly recomputing derivation values. I think both of them can become bottleneck in different cases.

Using immutable data-structures like [immutable-js](https://facebook.github.io/immutable-js/) can improve performance of comparing result of computation of derivation and detect whether its value has really changed or not.

**Comment by ds300** [comment]
>  I think both of them can become bottleneck in different cases.

This is very true, and I see value in being able to hand-optimize when necessary. I also think it would not be too invasive to add a derivation type with explicit static dependencies like you suggest, so will think carefully about doing that.
