### ISSUE TITLE
How to filter some atom changes?

### ISSUE THREAD

**Issue by zerkalica** [ds300/derivablejs#51]
How to filter some atom changes?

I think, withEquality is deprecated: not used in next version of derivablejs.

My bicycle. But this is mokey-patching of atom.set method:

```js

import shallowEqual from 'shallowequal'

function wrapAtomSet<V>(value: Atom<V>, isEqual: (old: V, new: V) => boolean) {
    const oldSet: (value: V) => void = value.set
    return function set(v: V): void {
        if (!isEqual(value.get(), v)) {
            oldSet.call(value, v)
        }
    }
}

const value = atom({a: 123})
value.set = wrapAtomSet(value, shallowEqual)
value.set({a: 123}) // does not really call set method
```

**Comment by andreypopp** [comment]
AFAIK `withEquality` is deprecated only at module level. But on any single atom/derivable it can be used safely.

**Comment by ds300** [comment]
> withEquality is deprecated only at module level. But on any single atom/derivable it can be used safely.

True. You can still do, e.g.

    const value = atom({a: 123}).withEquality(shallowEqual);
