### ISSUE TITLE
Api for timetravel and monitoring state changes

### ISSUE THREAD

**Issue by zerkalica** [ds300/derivablejs#53]
I think about devtool like in redux on top of derivable: tracking state changes and timetravel.

Do you plain do something in derivablejs? May be to create some hooks in atom api for intercepting state changes?

My first naive implementation for undo/redo with atom monkey-patching:

``` js
import {atom} from 'derivable'

class Wrapper {
  _changes: {atom: Atom, val: mixed}[] = []
  _pos: number = 0
  _logChanges: (from: mixed, to: mixed) => void

  constructor(logChanges: (from: mixed, to: mixed) => void) {
    this._logChanges = logChanges
  }

  wrap(atom: Atom): Atom {
   const changes = this._changes
   changes.push({atom, val: atom.get()})
   this._pos++
   const set = (newValue) => {
       this._logChanges(atom.get(), newValue)
       changes.push({atom, val: newValue})
       this._pos++
   }

   return {...atom, set}
  }

  undo(): void {
     const changes = this._changes
     if (this._pos <= 1) return
     this._pos--
     const {atom, val} = changes[this._pos - 1]
     atom.set(val)
  }

  redo(): void {
     const changes = this._changes
     if (this._pos >= changes.length) return
     this._pos++
     const {atom, val} = changes[this._pos - 1]
     atom.set(val)
  }
}

const wrapper = new Wrapper((from, to) => {
  console.log('from', from, '\n', 'to', to)
})

const aAtom = atom(123)
const a = wraper.wrap(aAtom)

a.set(321)

wrapper.undo() // a === 123
wrapper.redo() // a === 321
```

**Comment by ds300** [comment]
I don't think you need to do monkey patching. First, you can monitor state changes with `Derivable#react`, that's it's whole job :) - Second, history can be done quite nicely with lenses. See the example below:

[https://github.com/ds300/derivablejs/blob/700c23fb96a800fa91f836d8a18158f7bf910bbc/examples/history/history.js](https://github.com/ds300/derivablejs/blob/700c23fb96a800fa91f836d8a18158f7bf910bbc/examples/history/history.js)

**Comment by TrySound** [comment]
Such feature can be introduced in [devtools](https://github.com/TrySound/derivable-devtools)
