### ISSUE TITLE
version 1.0.0-beta.12 instead of 1.0.0-beta12

### ISSUE THREAD

**Issue by wvanderdeijl** [ds300/derivablejs#56]
Hi,

We are using the 1.0.0 prerelease versions on our project. In subsequent versions could you please use a dot between the `beta` prerelease tag and the number?
So `1.0.0-beta.12` instead of `1.0.0-beta12`

This ensure we can use the following dependency in our package.json:
```
    "derivable": "^1.0.0-beta.9",
```
Currently the number is part of the prerelease tag itself, so beta9 is considered newer than beta11 (according to alphabet order) 

See https://github.com/npm/node-semver for more info.

**Comment by ds300** [comment]
Yes, of course, it makes sense. My apologies if this caused you any
problems. I wasn't expecting these beta releases to be around for so long.

**Comment by wvanderdeijl** [comment]
Unfortunately the new 1.0.0-beta.12 doesn't really solve the issue.
If I have my dependency like `^1.0.0-beta.12` it will still use `1.0.0-beta9` as the prerelease tag `beta9` is considered greater than `beta`.
I could get it to work to use a dependency like `1.0.0-beta.x ^1.0.0-beta.12` to get the latest beta release. Downside of this one is that it won't pick up the final 1.0.0 release as I require the beta.x pattern.

I guess there is not much you can do at your end as I think npm no longer allows unpublishing the wrong versions. The only thing you could do is forget about the 1.0.0 range and bump it to `1.0.1-beta.x` or `1.1.0-beta.x` but that would mean you probably never release a 1.0.0 final.

You can play around with semver at https://runkit.com/wvanderdeijl/58be856b25fc1f0014569583 to see for yourself and try alternatives

**Comment by TrySound** [comment]
@wvanderdeijl Does this issue matter with 2.0.0-beta.1?
