### ISSUE TITLE
Supply derivable to when and until

### ISSUE THREAD

**Issue by wvanderdeijl** [ds300/derivablejs#58]
Hi,

Would it be possible to pass the derivable as first argument to the `when` and `until` callbacks, or perhaps set `this` to the derivable when calling `when` or `until`? If so, I could create a PR for this, but I want to ask you first if you are willing to accept such a PR.

This simplifies the following example where we only want to react to even values:
```
let d = atom().derive(foo)
d.react(() => {...}, {when:() => d.get()%2==0} )
```

In the example we first need to create the `d` variable as we also have to reference it in the `when`. This can be more compact if the first argument to the `when` callback is the derivable itself:
```
atom().derive(foo).react(() => {...}, {when:d => d.get()%2==0} )
```

**Comment by ds300** [comment]
Would there be any reason not to pass the unpacked value in? e.g. 

```
atom().derive(foo).react(() => {...}, {when: d => d % 2 == 0} )
```

**Comment by wvanderdeijl** [comment]
Not really. Unpacked value would even be simpler. 
Should I submit a PR for that?

**Comment by wvanderdeijl** [comment]
Issue #33 seems to make a sensible case for not getting the current value every time we invoke a when (or until) as the invocation of the get() might record it as a dependency even if the function doesn't actually use it. This would mean passing the derivable itself is a more sensible choice and if the function would invoke the get() it would mark as a dependency
