### ISSUE TITLE
Merge `derivation` into `derive` and remove `lift`

### ISSUE THREAD

**Issue by ds300** [ds300/derivablejs#61]
At the moment the `derive` function is only used for tagged template strings. I think it should still be used for that, but that it should also be used for the same purpose as `derivation` currently is, and in some ways should mirror the `.derive` method in accepting extra arguments.

e.g.

- `x.derive(f)` should be equivalent to `derive(f, x)` should be equivalent to `derive(() => f(x.get()))`
- `x.derive(f, y)` should be equivalent to `derive(f, x, y)` should be equivalent to `derive(() => f(x.get(), y.get()))`

and so on.

w/r/t/ replacing `lift`:

`lift(f)(x, y)` now becomes `derive(f, x, y)` and `lift(f)` becomes `derive.bind(null, f)` or equivalent, if you're using some nifty library with partial function application.

**Comment by oskbor** [comment]
should 
```
derive('myProp', myAtom)
derive(/regex/, myAtom)
etc...
```
be legal?
Its no problem to support numbers, strings, regex, the issue is currently only with Array
since
```
derive(['propA', 'propB'], myAtom)
and derive`some template string ${myAtom}`
```
shows up with the same signature. However, the array has a `raw` property in the template string case. Can I rely on that property to distinguish the two cases?

**Comment by ds300** [comment]
No, I think the `derive` function should only work with a function as the first argument, or as a tagged template string function.

So the acceptable signatures are:

```typescript
derive<R>(f: () => R): Derivable<R>
derive<R, A>(f: A => R, a: A | Derivable<A>): Derivable<R>
derive<R, A, B>(f: A => R, a: A | Derivable<A>, b: B | Derivable<B>): Derivable<R>
// ... and so on up to D
derive(sections: string[], values: any[]): Derivable<string>
```

And anything else should be an error

**Comment by oskbor** [comment]
Ok, great!
But all the existing signatures for `atom.derive()` should remain as is? String regex etc

**Comment by ds300** [comment]
I've often though maybe RegExp is a bit excessive. What do you think?
