### ISSUE TITLE
deriver function is never called.

### ISSUE THREAD

**Issue by fiatjaf** [ds300/derivablejs#67]
I'm just getting started and puzzled by this behavior that looks counterintuitive to me.

When my code reaches [this](https://github.com/fiatjaf/coisas/blob/a20ece06992739d0d8071d71720d490a9c3a8f22/state.js#L85) point, it attempts to use a value that is derived from another value that has just been set.

However, calling `.get()` on the derived value yields an empty string: `''`.

At the same time, [none of the derive functions](https://github.com/fiatjaf/coisas/blob/a20ece06992739d0d8071d71720d490a9c3a8f22/state.js#L13-L21) that should have been called are called. I've set up breakpoints there and so on. Nothing.

Is this some issue related to asynchronicity? Please help me.

**Comment by ds300** [comment]
The code looks OK to me. Happy to debug for you. I tried running it but can't figure out how. Any chance you could set up a minimal project which reproduces the issue?

**Comment by fiatjaf** [comment]
Thank you, @ds300! Is it ok if you open it directly on my development server 

https://cantillon.alhur.es:2764/#!/fiatjaf/levypla/blogue/o-filho-do-rico.md

**Comment by ds300** [comment]
Hmm looks like you were using the latest API with changes from @oskbor earlier this year, but I hadn't published that stuff yet because I'm stupid. Just published it to npm under version `2.0.0-beta.0`. Hope that fixes your issues!

**Comment by fiatjaf** [comment]
Oh, that has fixed it. Thank you very much!

I was using the `1.0.0-beta.12` version along with guidelines from the README (not the docs page) because it looked like `react-derivable` needed this.
