### ISSUE TITLE
Some reactions not being triggered

### ISSUE THREAD

**Issue by fiatjaf** [ds300/derivablejs#68]
Specifically, when I call [`state.tree.set()` here](https://github.com/fiatjaf/coisas/blob/698114176a740b00ee408d6c164c934c7a410ce7/state.js#L105) it then triggers [this reaction which calls `tree.set()` again](https://github.com/fiatjaf/coisas/blob/698114176a740b00ee408d6c164c934c7a410ce7/state.js#L136), but this in its turn does not cause [this React component](https://github.com/fiatjaf/coisas/blob/698114176a740b00ee408d6c164c934c7a410ce7/components/Repo.js#L23-L29) to be rerendered.

Since I'm using [react-derivable](https://github.com/andreypopp/react-derivable) I thought it could be a problem there. I tried hard to debug it and concluded that no, the [reactors it sets to trigger the component updates](https://github.com/andreypopp/react-derivable/blob/3593e7e0607905901fc06616ab3d48b942503188/src/index.js#L35) are doing well.

The problem, as far as I could understand, appears to be happening at the [`maybeReact`](https://github.com/ds300/derivablejs/blob/4989b53c579a813de472bf43bb18bbda35a31f1e/src/reactors.js#L57) method, in which `this._parent._state` is not set to `CHANGED` when it comes the time of `state.tree` to be evaluated (I actually got quite confused with the governors and deeply nested reaction parent/children).

Perhaps I shouldn't be updating the same atom in a reaction that was caused by its own update? (In my defense, I'm not quite doing that, the reaction I've set up is dependent on a different atom, it just happens to update an atom that has just been updated in the same transaction.)

**Comment by ds300** [comment]
Try calling the nested tree.set after a `setImmediate` or `setTimeout`. DerivableJS doesn't support synchronously cyclical reactions.

If that doesn't work, I can try debugging tomorrow some time.

**Comment by fiatjaf** [comment]
That worked. I should have tried it before opening the issue.

But perhaps the API could be improved here. The way it is, I would have thought that the reaction would depend only on the atom from which it was declared, but that's not the case (for example, in `atomA.react(reactionX)` `reactionX` appears to be dependent only on `atomA`, but if `reactionX` calls `atomB.get()` in its body then it is dependent on `atomB` also, right?).

So perhaps it would be better to just call `reaction([atomA, atomB], (a, b) => {})` or even `reaction(() => { atomA.get(), atmoB.get() })`. It's probably possible to do these already, I'm just saying it because I thought it could be made clearer.

Or maybe I'm totally wrong and there's not such stated dependency relation at all.
